services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\OrderPrinter\Infra\Cups\ReceiptPrinter: ~
    Veliu\OrderPrinter\Domain\Receipt\ReceiptPrinterInterface: '@Veliu\OrderPrinter\Infra\Cups\ReceiptPrinter'

