services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\OrderPrinter\Infra\Printer\Epson\ReceiptFormatter: ~
    Veliu\OrderPrinter\Domain\Receipt\ReceiptFormatterInterface: '@Veliu\OrderPrinter\Infra\Printer\Epson\ReceiptFormatter'

