services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\OrderPrinter\Infra\EscPos\PrintProcessor: ~
    Veliu\OrderPrinter\Domain\Service\PrintOrderProcessorInterface: '@Veliu\OrderPrinter\Infra\EscPos\PrintProcessor'
