imports:
    - { resource: 'services/shopware.yaml' }
    - { resource: 'services/epson.yaml' }
    - { resource: 'services/cups.yaml' }
    - { resource: 'services/escpos.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # CLI COMMANDS
    Veliu\OrderPrinter\Adapter\Command\PrintOrderCommand: ~

    Veliu\OrderPrinter\Domain\Service\DefaultPrintOrderProcessor: ~

    Veliu\OrderPrinter\Domain\Receipt\ReceiptGenerator: ~
    Veliu\OrderPrinter\Domain\Receipt\ReceiptGeneratorInterface: '@Veliu\OrderPrinter\Domain\Receipt\ReceiptGenerator'

    Veliu\OrderPrinter\Infra\Symfony\FileSystem\ReceiptSaver: ~
    Veliu\OrderPrinter\Domain\Receipt\ReceiptSaverInterface: '@Veliu\OrderPrinter\Infra\Symfony\FileSystem\ReceiptSaver'

    Veliu\OrderPrinter\Infra\Symfony\Scheduler\OpenOrderProvider: ~

    # MESSAGE HANDLER
    Veliu\OrderPrinter\Domain\Command\PrintOrderHandler: ~
    Veliu\OrderPrinter\Domain\Command\PrintOpenOrdersHandler: ~
